In [7]:
import numpy as np

np.array([1, 2, 3, 4])

np.arange(9, 30, 3) # 3. argument for at hoppe

np.linspace(0, 2 * np.pi, 5)

array([ 0.        ,  1.57079633,  3.14159265,  4.71238898,  6.28318531])

In [10]:
data = np.arange(9, 30, 3) # 3. argument for at hoppe
print(data)
data[2:-2:2]

[ 9 12 15 18 21 24 27]


array([15, 21])

In [12]:
np.arange(36).reshape(3, 3, 4)  #.shape z y x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [18]:
a = np.arange(11, 36).reshape(5, 5)
a

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [55]:
a = np.arange(11, 36).reshape(5, 5)
#a[0:5, 1:2] # Lodret lilla 12, 17, 22, 27, 32
a[:, 1:2] # Lodret lilla som er mere generiks
#a[0, 1:4] # Vandret rød 12, 13, 14 [ 1, 4 [ - 1 er med og 3 er med men ikke 4!
#a[1:-1, 0] # Lodret blå
#a[::2, ::2] # Grøn som spiller hver anden over og hver anden række over

array([[12],
       [17],
       [22],
       [27],
       [32]])

In [91]:
import pandas as pd
filename = './befkbhalderstatkode.csv'

bef_stats_df = pd.read_csv(filename)
dd = bef_stats_df.as_matrix()


ImportError: cannot import name 'isna'